version: "3.9"

services:
  db:
    image: mariadb:11
    container_name: simple-ci-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: simple-ci
      MARIADB_USER: yemre
      MARIADB_PASSWORD: 574563
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  app:
    image: simple-ci-demo:local
    container_name: simple-ci-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/simple-ci
      SPRING_DATASOURCE_USERNAME: yemre
      SPRING_DATASOURCE_PASSWORD: 574563
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mariadb_data:
