spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/simple-ci}
    username: ${SPRING_DATASOURCE_USERNAME:yemre}
    password: ${SPRING_DATASOURCE_PASSWORD:574563}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

